### ISSUE TITLE
Help text for xmpp_notify_recv is misleading

### ISSUE THREAD

**Issue by tgr** [dm8tbr/irssi-jabber-notify#8]
Irssi::print('%G>>%n xmpp_notify_user : Set to xmpp account to send from.');
    Irssi::print('%G>>%n xmpp_notify_recv : Set to xmpp account to receive message.');

This suggest that the two are of the same type, but actually one of them is a username and the other is a full address. Irssi not being a great environment for debugging, it took me a while to track down why the notification is not working.

**Comment by dm8tbr** [comment]
Yeah, didn't come up with a better wording back then. Let me give those a quick do over.
