### ISSUE TITLE
Add debug option

### ISSUE THREAD

**Issue by tgr** [dm8tbr/irssi-jabber-notify#9]
To better analyze connection problems, there should be a way to set the debug options in Net::Jabber::Client. I am thinking of adding an `xmpp_notify_debug_file` option, and if that's non-empty, `debuglevel => 2, debugtime => 1, debugfile => <xmpp_notify_debug_file>` will be added to the connection's parameters.

Will provide a patch once #7 is merged, if you think this is the right approach. (I would need it to debug what I think are auth timeout problems with the script.)

**Comment by dm8tbr** [comment]
go ahead, sounds good. Please note that I made the CA path configurable after merging #7, so you'll probably have to rebase your changes.
